"""empty message

Revision ID: b1cba554500b
Revises: cc8d2c759ac8
Create Date: 2025-03-16 05:31:39.594132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b1cba554500b'
down_revision: Union[str, None] = 'cc8d2c759ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query')
    with op.batch_alter_table('userattribute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_collections', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userattribute', schema=None) as batch_op:
        batch_op.drop_column('user_collections')

    op.create_table('query',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_attribute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_attribute_id'], ['userattribute.id'], name='query_user_attribute_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='query_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='query_pkey')
    )
    # ### end Alembic commands ###
