"""empty message

Revision ID: c912fe6c51a5
Revises: 7040da41ce0d
Create Date: 2025-03-12 10:19:50.584181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c912fe6c51a5'
down_revision: Union[str, None] = '7040da41ce0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Float(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adminconfig', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adminconfig_name'), ['name'], unique=True)

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index('ix_workflow_name')

    op.drop_table('workflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.FLOAT(), nullable=False),
    sa.Column('configuration', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_name', ['name'], unique=1)

    with op.batch_alter_table('adminconfig', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adminconfig_name'))

    op.drop_table('adminconfig')
    # ### end Alembic commands ###
