"""empty message

Revision ID: cc8d2c759ac8
Revises: 521c85a96a29
Create Date: 2025-03-15 18:48:13.466736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cc8d2c759ac8'
down_revision: Union[str, None] = '521c85a96a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_attribute_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'userattribute', ['user_attribute_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_attribute_id')

    # ### end Alembic commands ###
